### ISSUE TITLE
Possible to build for macOS but with g++ and not clang?

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/qcdloop-feedstock#5]
@chrisburr, as QCDLoop uses `quadmath` , which is not yet supported by `clang` (AFAIK)

https://github.com/conda-forge/qcdloop-feedstock/blob/b5bfd3de8e36024f3f2621471f8b472a7bf906ae/recipe/meta.yaml#L21

the QCDLoop developers have done all of their macOS testing using `g++` (c.f. https://github.com/scarrazza/qcdloop/issues/26#issuecomment-2469615057).

Is it possible for a conda-forge feedstock to indicate to the macOS CI jobs that

https://github.com/conda-forge/qcdloop-feedstock/blob/b5bfd3de8e36024f3f2621471f8b472a7bf906ae/recipe/meta.yaml#L38

should resolve to

https://github.com/conda-forge/qcdloop-feedstock/blob/b5bfd3de8e36024f3f2621471f8b472a7bf906ae/.ci_support/linux_64_.yaml#L11-L14

instead of

```yaml
cxx_compiler:
- clangxx
cxx_compiler_version:
- '18'
```
? Or is that going to be a huge pain / result in other issues later on for environment solves?

**Comment by matthewfeickert** [comment]
@ocefpaf, if I can abuse your incredible helpfulness and deep knowledge to also ask you about this, I'd be curious on your general thoughts (which may very well be "never do this").

**Comment by ocefpaf** [comment]
This is more of a @isuruf question. I vaguely recall that he already explained that to me at some point...

**Comment by isuruf** [comment]
No, we don't support gxx on macOS since libstdc++ and libc++ are not ABI compatible.

**Comment by matthewfeickert** [comment]
Thanks @isuruf.
